#!/usr/bin/env node
const Octokat = require('octokat');
const YAML = require('yamljs');
const path = require('path');
const fs = require('fs');

var config = YAML.load(path.join(process.env.HOME, '.config/hub'));
var hub = new Octokat({token: config['github.com'][0].oauth_token});
var repo_name = path.basename(process.cwd());
var description = fs.readFileSync('description', {encoding: 'utf-8'});
hub.repos('freedesktop-unofficial-mirror', repo_name).update({name: repo_name, description: description + ' (mirror)'}, function(err) {
  if (err) {
    process.exitCode = 1;
    console.error(err);
  }
});
